git clone https://github.com/paragonie/past.git
git clone https://github.com/laravel/laravel.git
git clone https://github.com/symfony/thanks.git
git clone https://github.com/composer/composer.git
git clone https://github.com/php-pm/php-pm.git
git clone https://github.com/mikeerickson/phpunit-pretty-result-printer.git
git clone https://github.com/Seldaek/monolog.git
git clone https://github.com/doctrine/inflector.git
git clone https://github.com/symfony/symfony.git
git clone https://github.com/sebastianbergmann/phpunit.git
git clone https://github.com/fzaninotto/Faker.git
git clone https://github.com/symfony/console.git
git clone https://github.com/laravel/framework.git
git clone https://github.com/symfony/debug.git
git clone https://github.com/symfony/event-dispatcher.git
git clone https://github.com/swiftmailer/swiftmailer.git
git clone https://github.com/symfony/finder.git
git clone https://github.com/guzzle/guzzle.git
git clone https://github.com/symfony/http-foundation.git
git clone https://github.com/phpDocumentor/ReflectionDocBlock.git
git clone https://github.com/sebastianbergmann/php-timer.git
git clone https://github.com/symfony/routing.git
git clone https://github.com/phpDocumentor/TypeResolver.git
git clone https://github.com/symfony/http-kernel.git
git clone https://github.com/sebastianbergmann/exporter.git
git clone https://github.com/sebastianbergmann/php-code-coverage.git
git clone https://github.com/phpDocumentor/ReflectionCommon.git
git clone https://github.com/nikic/PHP-Parser.git
git clone https://github.com/symfony/process.git
git clone https://github.com/sebastianbergmann/phpunit-mock-objects.git
git clone https://github.com/sebastianbergmann/comparator.git
git clone https://github.com/composer/installers.git
git clone https://github.com/FriendsOfPHP/pickle.git
git clone https://github.com/joshdifabio/composed.git
git clone https://github.com/silpion/composer-checker.git
git clone https://github.com/wikimedia/composer-merge-plugin.git
git clone https://github.com/bamarni/composition.git
git clone https://github.com/ralphschindler/Namespacer.git
git clone https://github.com/goatherd/patch-installer.git
git clone https://github.com/hirak/prestissimo.git
git clone https://github.com/composer/satis.git
git clone https://github.com/tommy-muehle/tooly-composer-script.git
git clone https://github.com/ppi.git
git clone https://github.com/yiisoft/yii2/.git
git clone https://github.com/friendsofcake/crud.git
git clone https://github.com/symfony-cmf/symfony-cmf.git
git clone https://github.com/alexbilbie/Proton.git
git clone https://github.com/radarphp/Radar.Adr.git
git clone https://github.com/silexphp/Silex-Skeleton.git
git clone https://github.com/silexphp/Silex-WebProfiler.git
git clone https://github.com/slimphp/Slim-Skeleton.git
git clone https://github.com/slimphp/Slim-Views.git
git clone https://github.com/auraphp/Aura.Router.git
git clone https://github.com/nikic/FastRoute.git
git clone https://github.com/klein/klein.php.git
git clone https://github.com/c9s/Pux.git
git clone https://github.com/thephpleague/route.git
git clone https://github.com/auraphp/Aura.View.git
git clone https://github.com/FoilPHP/Foil.git
git clone https://github.com/pyrocms/lex.git
git clone https://github.com/arnaud-lb/MtHaml.git
git clone https://github.com/bobthecow/mustache.php.git
git clone https://github.com/phly/phly_mustache.git
git clone https://github.com/Talesoft/tale-jade.git
git clone http://couscous.io.git
git clone https://github.com/Pawka/phrozn.git
git clone https://github.com/kriswallsmith/Buzz.git
git clone https://github.com/nategood/httpful.git
git clone http://php-vcr.github.io/.git
git clone https://github.com/rmccue/Requests.git
git clone https://github.com/tebru/retrofit-php.git
git clone https://github.com/zendframework/zend-diactoros.git
git clone https://github.com/oscarotero/Embed.git
git clone https://github.com/FriendsOfPHP/Goutte.git
git clone https://github.com/mvdbos/php-spider.git
git clone https://zendframework.github.io/zend-expressive.git
git clone https://github.com/oscarotero/psr7-middlewares.git
git clone https://github.com/relayphp/Relay.Relay.git
git clone https://github.com/stackphp.git
git clone https://github.com/zendframework/zend-stratigility.git
git clone https://github.com/jeremykendall/php-domain-parser.git
git clone https://github.com/jwage/purl.git
git clone https://github.com/sabre-io/uri.git
git clone https://github.com/thephpleague/uri.git
git clone https://github.com/tijsverkoyen/CssToInlineStyles.git
git clone https://github.com/willdurand/EmailReplyParser.git
git clone https://github.com/nojacko/email-validator.git
git clone https://github.com/tedious/Fetch.git
git clone https://github.com/mautic/mautic.git
git clone https://github.com/PHPMailer/PHPMailer.git
git clone https://github.com/Stampie/Stampie.git
git clone https://github.com/dflydev/dflydev-apache-mime-types.git
git clone https://github.com/dflydev/dflydev-canal.git
git clone https://github.com/thephpleague/csv.git
git clone https://github.com/versionable/Ferret.git
git clone https://github.com/thephpleague/Flysystem.git
git clone https://github.com/KnpLabs/Gaufrette.git
git clone https://github.com/hoaproject/Mime.git
git clone https://github.com/henrikbjorn/Lurker.git
git clone https://github.com/PHP-FFmpeg/PHP-FFmpeg/.git
git clone https://github.com/wapmorgan/UnifiedArchive.git
git clone https://github.com/fzaninotto/Streamer.git
git clone https://github.com/auraphp/Aura.Di.git
git clone https://github.com/AcclimateContainer/acclimate-container.git
git clone https://github.com/rdlowrey/Auryn.git
git clone https://github.com/thephpleague/container.git
git clone https://github.com/bitExpert/disco.git
git clone https://github.com/symfony/dependency-injection.git
git clone https://github.com/thephpleague/color-extractor.git
git clone https://github.com/Sybio/GifCreator.git
git clone https://github.com/Sybio/GifFrameExtractor.git
git clone https://github.com/thephpleague/glide.git
git clone https://github.com/jenssegers/imagehash.git
git clone https://github.com/psliwa/image-optimizer.git
git clone https://github.com/nmcteam/image-with-text.git
git clone https://github.com/Intervention/image.git
git clone https://github.com/Sybio/ImageWorkshop.git
git clone https://github.com/nelmio/alice.git
git clone https://github.com/Codeception/AspectMock.git
git clone https://github.com/atoum/atoum.git
git clone https://github.com/Codeception/Codeception.git
git clone https://github.com/sebastianbergmann/dbunit.git
git clone https://github.com/InterNations/http-mock.git
git clone https://github.com/kahlan/kahlan.git
git clone https://github.com/mockery/mockery.git
git clone https://github.com/brianium/paratest.git
git clone https://github.com/peridot-php/peridot.git
git clone https://github.com/mlively/Phake.git
git clone https://github.com/danielstjules/pho.git
git clone https://github.com/php-mock/php-mock.git
git clone https://github.com/phpspec/phpspec.git
git clone https://github.com/phpspec/prophecy.git
git clone https://github.com/mauris/samsui.git
git clone https://github.com/mikey179/vfsStream.git
git clone https://github.com/adlawson/php-vfs.git
git clone https://github.com/jolicode/JoliCi.git
git clone https://github.com/apigen/apigen.git
git clone https://github.com/justinwalsh/daux.io.git
git clone https://github.com/phpDocumentor/phpDocumentor2.git
git clone https://github.com/FriendsOfPHP/Sami.git
git clone https://paragonie.com/project/halite.git
git clone https://github.com/ezyang/htmlpurifier.git
git clone https://github.com/psecio/iniscan.git
git clone https://github.com/jenssegers/optimus.git
git clone https://github.com/defuse/php-encryption.git
git clone https://github.com/PHPIDS/PHPIDS.git
git clone https://github.com/Herzult/php-ssh.git
git clone https://github.com/paragonie/random_compat.git
git clone https://github.com/ircmaxell/RandomLib.git
git clone https://github.com/padraic/SecurityMultiTool.git
git clone https://github.com/timoh6/TCrypto.git
git clone https://github.com/timoh6/GenPhrase.git
git clone https://github.com/ircmaxell/password_compat.git
git clone https://github.com/ircmaxell/password-policy.git
git clone https://github.com/jeremykendall/password-validator.git
git clone https://github.com/hackzilla/password-generator.git
git clone https://github.com/ircmaxell/PHP-PasswordLib.git
git clone https://github.com/bjeavons/zxcvbn-php.git
git clone https://github.com/Roave/BetterReflection.git
git clone https://github.com/tomzx/php-semver-checker.git
git clone https://github.com/sebastianbergmann/phploc.git
git clone https://github.com/EdgedesignCZ/phpqa.git
git clone https://github.com/Qafoo/QualityAnalyzer.git
git clone https://scrutinizer-ci.com.git
git clone https://github.com/devster/ubench.git
git clone https://github.com/squizlabs/PHP_CodeSniffer.git
git clone https://github.com/FriendsOfPHP/PHP-CS-Fixer.git
git clone https://github.com/PHPCheckstyle/phpcheckstyle.git
git clone https://github.com/sebastianbergmann/phpcpd.git
git clone https://github.com/exakat/exakat.git
git clone https://github.com/Trismegiste/Mondrian.git
git clone https://github.com/phan/phan.git
git clone https://github.com/wimg/PHPCompatibility.git
git clone https://github.com/mamuz/PhpDependencyAnalysis.git
git clone https://github.com/phpmetrics/PhpMetrics.git
git clone https://github.com/monque/PHP-Migration.git
git clone https://github.com/phpstan/phpstan.git
git clone https://github.com/vimeo/psalm.git
git clone https://github.com/igorw/compose.git
git clone https://github.com/domnikl/DesignPatternsPHP.git
git clone https://github.com/lstrojny/functional-php.git
git clone https://github.com/endel/galapagos.git
git clone https://github.com/nikic/iter.git
git clone https://github.com/ircmaxell/monad-php.git
git clone https://github.com/schmittjoh/php-option.git
git clone https://github.com/thephpleague/pipeline.git
git clone https://github.com/bobthecow/Ruler.git
git clone https://github.com/K-Phoen/rulerz.git
git clone https://github.com/barbushin/php-console.git
git clone https://github.com/kint-php/kint.git
git clone https://github.com/Seldaek/php-console.git
git clone https://github.com/phpbench/phpbench.git
git clone https://github.com/nette/tracy.git
git clone https://github.com/xdebug/xdebug.git
git clone https://github.com/phacility/xhprof.git
git clone https://github.com/CHH/bob.git
git clone https://github.com/box-project/box2.git
git clone https://github.com/jonathantorres/construct.git
git clone https://github.com/jaz303/phake.git
git clone https://github.com/jobbyphp/jobby.git
git clone https://github.com/consolidation/Robo.git
git clone http://taskphp.github.io.git
git clone https://github.com/KnpLabs/KnpMenu.git
git clone https://github.com/tedious/JShrink.git
git clone https://github.com/meenie/munee.git
git clone https://github.com/puli/repository.git
git clone https://github.com/Bee-Lab/bowerphp.git
git clone https://github.com/jmikola/geojson.git
git clone https://github.com/thephpleague/geotools.git
git clone https://github.com/mjaschen/phpgeo.git
git clone https://github.com/briannesbitt/Carbon.git
git clone https://github.com/cakephp/chronos.git
git clone https://github.com/fightbulc/moment.php.git
git clone https://github.com/azuyalabs/yasumi.git
git clone https://github.com/amphp/amp.git
git clone https://github.com/broadway/broadway.git
git clone https://github.com/cakephp/event.git
git clone https://github.com/Wisembly/Elephant.io.git
git clone https://github.com/igorw/evenement.git
git clone https://github.com/thephpleague/event.git
git clone https://github.com/hoaproject/Eventsource.git
git clone https://github.com/hoaproject/Websocket.git
git clone https://github.com/prooph/event-store.git
git clone https://github.com/ratchetphp/Ratchet.git
git clone https://github.com/reactphp/react.git
git clone https://github.com/asm89/Rx.PHP.git
git clone https://github.com/walkor/Workerman.git
git clone https://github.com/moneyphp/money.git
git clone https://github.com/thephpleague/omnipay.git
git clone https://github.com/payum/payum.git
git clone https://github.com/shopware/shopware.git
git clone https://github.com/florianv/swap.git
git clone https://github.com/dompdf/dompdf.git
git clone https://github.com/psliwa/PHPPdf.git
git clone https://github.com/KnpLabs/snappy.git
git clone https://github.com/wkhtmltopdf/wkhtmltopdf.git
git clone https://github.com/Wisembly/ExcelAnt.git
git clone https://github.com/PHPOffice/PHPPresentation.git
git clone https://github.com/PHPOffice/PHPWord.git
git clone https://github.com/PHPOffice/PhpSpreadsheet.git
git clone https://github.com/atlasphp/Atlas.Orm.git
git clone https://github.com/auraphp/Aura.Sql.git
git clone https://github.com/auraphp/Aura.SqlQuery.git
git clone https://github.com/etrepat/baum.git
git clone https://github.com/cakephp/orm.git
git clone https://github.com/Atlantic18/DoctrineExtensions.git
git clone https://github.com/illuminate/database.git
git clone https://github.com/corneltek/LazyRecord.git
git clone https://github.com/chanmix51/Pomm.git
git clone https://github.com/Ocramius/ProxyManager.git
git clone https://github.com/spotorm/spot2.git
git clone https://github.com/icomefromthenet/Migrations.git
git clone https://github.com/cakephp/phinx.git
git clone https://github.com/davedevelopment/phpmig.git
git clone https://github.com/ruckus/ruckusing-migrations.git
git clone https://github.com/thephpleague/monga.git
git clone https://github.com/alexbilbie/MongoQB.git
git clone https://github.com/sokil/php-mongo.git
git clone https://github.com/nrk/predis.git
git clone https://github.com/bernardphp/bernard.git
git clone https://github.com/jakubkulhan/bunny.git
git clone https://github.com/pda/pheanstalk.git
git clone https://github.com/php-amqplib/php-amqplib.git
git clone https://github.com/tarantool-php/queue.git
git clone https://github.com/php-amqplib/Thumper.git
git clone https://github.com/ruflin/Elastica.git
git clone https://github.com/elastic/elasticsearch-php.git
git clone https://github.com/ripaclub/sphinxsearch.git
git clone http://foolcode.github.io/SphinxQL-Query-Builder.git
git clone https://github.com/auraphp/Aura.Cli.git
git clone https://github.com/borisrepl/boris.git
git clone https://github.com/Cilex/Cilex.git
git clone https://github.com/php-school/cli-menu.git
git clone https://github.com/c9s/CLIFramework.git
git clone https://github.com/thephpleague/climate.git
git clone https://github.com/nategood/commando.git
git clone https://github.com/mtdowling/cron-expression.git
git clone https://github.com/getopt-php/getopt-php.git
git clone https://github.com/c9s/GetOptionKit.git
git clone https://github.com/hoaproject/Console.git
git clone https://github.com/CHH/optparse.git
git clone https://github.com/mcrumm/pecan.git
git clone https://github.com/bobthecow/psysh.git
git clone https://github.com/MrRio/shellwrap.git
git clone https://github.com/auraphp/Aura.Auth.git
git clone https://github.com/dflydev/dflydev-hawk.git
git clone https://github.com/socialConnect/auth.git
git clone https://github.com/lcobucci/jwt.git
git clone https://github.com/thephpleague/oauth1-client.git
git clone https://github.com/thephpleague/oauth2-client.git
git clone http://bshaffer.github.io/oauth2-server-php-docs.git
git clone https://github.com/opauth/opauth.git
git clone https://github.com/Lusitanian/PHPoAuthLib.git
git clone https://github.com/abraham/twitteroauth.git
git clone https://github.com/lyrixx/twitter-sdk.git
git clone https://github.com/cebe/markdown.git
git clone https://github.com/kzykhys/Ciconia.git
git clone https://github.com/thephpleague/commonmark.git
git clone https://github.com/milesj/decoda.git
git clone https://github.com/heyupdate/Emoji.git
git clone https://github.com/thephpleague/html-to-markdown.git
git clone https://github.com/Masterminds/html5-php.git
git clone https://github.com/erusev/parsedown.git
git clone https://github.com/michelf/php-markdown.git
git clone https://github.com/jenssegers/agent.git
git clone https://github.com/sensiolabs/ansi-to-html.git
git clone https://github.com/mikeemoo/ColorJizz-PHP.git
git clone https://github.com/piwik/device-detector.git
git clone https://github.com/hoaproject/Ustring.git
git clone https://github.com/fukuball/jieba-php.git
git clone https://github.com/serbanghita/Mobile-Detect.git
git clone https://github.com/nicolas-grekas/Patchwork-UTF8.git
git clone https://github.com/cocur/slugify.git
git clone https://github.com/jdorn/sql-formatter/.git
git clone https://github.com/danielstjules/Stringy.git
git clone https://github.com/kzykhys/Text.git
git clone https://github.com/tobie/ua-parser/tree/master/php.git
git clone https://github.com/jbroadway/urlify.git
git clone https://github.com/ramsey/uuid.git
git clone https://github.com/gabrielelana/byte-units.git
git clone https://github.com/giggsey/libphonenumber-for-php.git
git clone https://github.com/moontoast/math.git
git clone https://github.com/powder96/numbers.php.git
git clone https://github.com/Crisu83/php-conversion.git
git clone https://github.com/triplepoint/php-units-of-measure.git
git clone https://github.com/auraphp/Aura.Filter.git
git clone https://github.com/cakephp/validation.git
git clone https://github.com/rdohms/DMS-Filter.git
git clone https://github.com/ircmaxell/filterus.git
git clone https://github.com/ronanguilloux/IsoCodes.git
git clone https://github.com/romaricdrigon/MetaYaml.git
git clone https://github.com/Respect/Validation.git
git clone https://github.com/brandonsavage/Upload.git
git clone https://github.com/vlucas/valitron.git
git clone https://github.com/serkin/Volan.git
git clone https://github.com/zfcampus/zf-apigility-skeleton.git
git clone https://github.com/leedavis81/drest.git
git clone https://github.com/blongden/hal.git
git clone https://github.com/willdurand/Hateoas.git
git clone https://github.com/willdurand/Negotiation.git
git clone https://github.com/Luracast/Restler.git
git clone https://github.com/wsdl2phpgenerator/wsdl2phpgenerator.git
git clone https://github.com/apix/cache.git
git clone https://github.com/gordalina/cachetool.git
git clone https://github.com/cakephp/cache.git
git clone https://github.com/doctrine/cache.git
git clone https://github.com/sobstel/metaphore.git
git clone https://github.com/tedious/Stash.git
git clone https://github.com/zendframework/zend-cache.git
git clone https://github.com/morrisonlevi/Ardent.git
git clone https://github.com/cakephp/collection.git
git clone https://github.com/italolelis/collections.git
git clone https://github.com/thephpleague/fractal.git
git clone https://github.com/akanehara/ginq.git
git clone https://github.com/cweiske/jsonmapper.git
git clone https://github.com/DusanKasan/Knapsack.git
git clone https://github.com/schmittjoh/php-collection.git
git clone https://github.com/TimeToogo/Pinq.git
git clone https://github.com/ScriptFUSION/Porter.git
git clone https://github.com/schmittjoh/serializer.git
git clone https://github.com/Wisembly/Totem.git
git clone https://github.com/Athari/YaLinqo.git
git clone https://github.com/zendframework/zend-serializer.git
git clone https://github.com/jolicode/JoliNotif.git
git clone https://github.com/filp/nod.git
git clone https://github.com/Ph3nol/NotificationPusher.git
git clone https://github.com/mac-cain13/notificato.git
git clone https://github.com/namshi/notificator.git
git clone https://github.com/gomoob/php-pushwoosh.git
git clone https://github.com/deployphp/deployer.git
git clone https://github.com/laravel/envoy.git
git clone https://github.com/aerialls/Plum.git
git clone https://github.com/tamagokun/pomander.git
git clone https://github.com/rocketeers/rocketeer.git
git clone https://github.com/auraphp/Aura.Intl.git
git clone https://github.com/cakephp/i18n.git
git clone https://github.com/aws/aws-sdk-php.git
git clone http://campaignmonitor.github.io/createsend-php.git
git clone https://github.com/toin0u/DigitalOcean.git
git clone https://github.com/dropbox/dropbox-sdk-php.git
git clone https://github.com/dsyph3r/github-api3-php.git
git clone https://github.com/mailgun/mailgun-php.git
git clone https://github.com/KnpLabs/php-github-api.git
git clone https://github.com/gwkunze/S3StreamWrapper.git
git clone https://github.com/stripe/stripe-php.git
git clone https://github.com/twilio/twilio-php.git
git clone https://github.com/widop/twitter-oauth.git
git clone https://github.com/widop/twitter-rest.git
git clone https://github.com/phalcon/zephir.git
git clone https://github.com/doctrine/annotations.git
git clone https://github.com/botman/botman.git
git clone https://github.com/cakephp/utility.git
git clone https://github.com/adamnicholson/Chief.git
git clone https://github.com/ClassPreloader/ClassPreloader.git
git clone https://github.com/umpirsky/country-list.git
git clone https://github.com/mpratt/Embera.git
git clone https://github.com/essence/essence.git
git clone https://github.com/selvinortiz/flux.git
git clone https://github.com/alexandresalome/graphviz.git
git clone https://github.com/hprose/hprose-php.git
git clone https://github.com/Seldaek/jsonlint.git
git clone https://github.com/willdurand/JsonpCallbackValidator.git
git clone https://github.com/kakawait/Jumper.git
git clone https://github.com/raulfraile/Ladybug.git
git clone https://github.com/igorw/lambda-php.git
git clone https://github.com/beberlei/litecqrs-php.git
git clone https://github.com/beberlei/metrics.git
git clone https://github.com/ARCANEDEV/noCAPTCHA.git
git clone https://github.com/willdurand/nmap.git
git clone https://github.com/euskadi31/Opengraph.git
git clone https://github.com/whiteoctober/Pagerfanta.git
git clone https://github.com/Kitano/php-expression.git
git clone https://github.com/eymengunay/php-passbook.git
git clone https://github.com/ronanguilloux/php-gpio.git
git clone https://github.com/php-ai/php-ml.git
git clone https://github.com/phpcr/phpcr.git
git clone https://github.com/koriym/print_o.git
git clone https://github.com/lstrojny/Procrastinator.git
git clone https://github.com/prooph/service-bus.git
git clone https://github.com/liip/RMT.git
git clone https://github.com/sabre-io/vobject.git
git clone https://github.com/webfactory/slimdump.git
git clone https://github.com/kriswallsmith/spork.git
git clone https://github.com/EvanDotPro/Sslurp.git
git clone https://github.com/jeremeamia/super_closure.git
git clone http://anahkiasen.github.io/underscore-php.git
git clone https://github.com/filp/whoops.git
git clone https://github.com/Homebrew/homebrew-php.git
git clone https://github.com/phpbrew/phpbrew.git
git clone https://github.com/php-build/php-build.git
git clone https://github.com/CHH/phpenv.git
git clone https://github.com/jubianchi/phpswitch.git
git clone https://github.com/facebook/hhvm.git
git clone https://github.com/hippyvm/hippyvm.git
git clone https://github.com/CoderKungfu/php-queue.git
git clone https://github.com/sj26/mailcatcher.git
git clone https://github.com/cachethq/cachet.git
git clone https://github.com/mnapoli/phpBeanstalkdAdmin.git
git clone https://github.com/ErikDubbelboer/phpRedisAdmin.git
git clone https://github.com/phppgadmin/phppgadmin.git
git clone https://github.com/phpmyadmin/phpmyadmin.git
git clone https://github.com/getgrav/grav.git
git clone https://github.com/electerious/Lychee.git